services:
  source_postgres:
    image: postgres:15
    ports:
      - '5433:5432'
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:15
    ports:
      - '5434:5432'
    networks:
      - elt_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  elt_script:
    build:
      context: ./elt # Directory containing the Dockerfile and elt_script.py
      dockerfile: Dockerfile # Name of the Dockerfile, if it's something other than "Dockerfile", specify here
    command: ['python', 'elt_script.py']
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.4.7
    command: [
      "run", 
      "--profiles-dir",
       "/root", 
       "--project-dir", 
       "/dbt"
    ]
    networks:
      - elt_network
    volumes:
      - ./transforms:/dbt
      - ~/.dbt:/root
    environment:
      DBT_PROFILE: default
      DBT_TARGET: dev
    depends_on:
      elt_script:
        condition: service_completed_successfully

networks:
  elt_network:
    driver: bridge